[toolchain]

[features]
resolution = true
skip-lint = false

[programs.testnet]
redstone_sol = "5cKwbjiexA7SEBEKb1nEvkykuEWEJhKpJLYbYKTBCyXY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "./pusher/example-keypair.json"

[workspace]
members = ["programs/redstone-sol"]

[scripts]
test = "npm run test"
