[toolchain]

[features]
resolution = true
skip-lint = false
upgradeable = true
seeds = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
initialize = "ts-node migrations/initialize.ts"
update-signers-threshold = "ts-node migrations/update-signers-threshold.ts"
get-config-account = "ts-node migrations/get-config-account.ts"
